import React, { createContext, useContext, useState, ReactNode } from 'react';

export type InterfaceLanguage = 'fr' | 'en';

interface LanguageContextType {
  language: InterfaceLanguage;
  setLanguage: (lang: InterfaceLanguage) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.joinEvent': 'Rejoindre un événement',
    'nav.organizer': 'Espace Organisateur',
    'nav.speakerLink': 'Vous êtes orateur ? Cliquez ici',
    
    // Home page
    'home.tagline': 'Accédez à vos évènements, conférences et réunions dans la langue de votre choix.',
    'home.subtitle': 'Connectez, traduisez et communiquez sans effort entre les langues, en temps réel.',
    'home.speakers.title': 'Pour les Orateurs',
    'home.speakers.description': 'Interface intuitive pour gérer vos événements et surveiller la qualité de traduction en temps réel.',
    'home.listeners.title': 'Pour les Auditeurs',
    'home.listeners.description': 'Accès simple via QR code ou code événement. Écoutez dans la langue de votre choix avec une latence minimale.',
    'home.privacyPolicy': 'Politique de confidentialité',
    'home.termsOfService': 'Conditions d\'utilisation',
    
    // Listener page
    'listener.joinEvent': 'Rejoindre un événement',
    'listener.eventCode': 'Code événement',
    'listener.eventCodePlaceholder': 'Entrez le code de l\'événement',
    'listener.selectLanguage': 'Sélectionnez votre langue',
    'listener.connect': 'Se connecter',
    'listener.scanQR': 'Scanner le QR code',
    'listener.deviceInfo': 'Compatible avec tous les appareils modernes',
    'listener.live': 'EN DIRECT',
    'listener.disconnect': 'Déconnexion',
    'listener.audioPlayer': 'Lecteur Audio',
    'listener.volume': 'Volume',
    'listener.latency': 'Latence',
    'listener.listeners': 'Auditeurs',
    'listener.quality': 'Qualité',
    'listener.switchLanguage': 'Changer de langue',
    'listener.ms': 'ms',
    'listener.excellent': 'Excellente',
    'listener.realTimeTranslation': 'Traduction en temps réel',
    'listener.connection': 'Connexion',
    'listener.providedByOrganizer': 'Code fourni par l\'organisateur',
    'listener.enterCode': 'Ex: TECH2024-FR',
    'listener.translationLanguage': 'Langue de Traduction',
    'listener.scanQRCode': 'Scanner QR Code',
    'listener.scanQRDescription': 'Scannez le QR code affiché par l\'organisateur',
    'listener.deviceCompatibility': 'Compatible smartphone, tablette et ordinateur',
    'listener.encryption': '🔒 Chiffrement bout en bout • 📱 Compatible tous appareils',
    'listener.invalidEventCode': 'Code d\'événement invalide',
    'listener.languageNotAvailable': 'La langue sélectionnée n\'est pas disponible pour cet événement',
    'listener.connectionError': 'Impossible de se connecter. Veuillez réessayer',
    
    // Organizer page
    'organizer.dashboard': 'Tableau de bord',
    'organizer.dashboardTitle': 'Tableau de bord Glot',
    'organizer.dashboardSubtitle': 'Gérez vos événements et suivez vos sessions de traduction.',
    'organizer.title': 'Espace Organisateur',
    'organizer.subtitle': 'Gérez vos événements de traduction simultanée',
    'organizer.tabs.events': 'Événements',
    'organizer.tabs.myEvents': 'Mes Événements',
    'organizer.tabs.create': 'Créer',
    'organizer.tabs.stats': 'Stats',
    'organizer.tabs.account': 'Mon Compte',
    'organizer.logout': 'Se déconnecter',
    'organizer.supabaseRequired': 'Activation Supabase Requise',
    'organizer.supabaseDescription': 'Pour utiliser les fonctionnalités complètes (authentification, gestion d\'événements, base de données), activez l\'intégration Supabase en cliquant sur le bouton vert en haut à droite.',
    'organizer.tabs.glossaries': 'Glossaires',
    'organizer.tabs.monitoring': 'Monitoring',
    'organizer.tabs.settings': 'Paramètres',
    'organizer.myEvents': 'Mes Événements',
    'organizer.createEvent': 'Créer un Événement',
    'organizer.active': 'Actif',
    'organizer.scheduled': 'Programmé',
    'organizer.languages': 'Langues',
    'organizer.listeners': 'Auditeurs',
    'organizer.participants': 'Participants',
    'organizer.latency': 'Latence',
    'organizer.qrCode': 'QR Code',
    'organizer.glossary': 'Glossaire',
    'organizer.actions': 'Actions',
    'organizer.connected': 'connectés',
    'organizer.expected': 'attendus',
    'organizer.averageLatency': 'moyenne',
    'organizer.specializedGlossaries': 'Glossaires Spécialisés',
    'organizer.createGlossary': 'Créer un Glossaire',
    'organizer.terms': 'termes',
    'organizer.lastUpdate': 'Dernière mise à jour',
    'organizer.realTimeMonitoring': 'Monitoring Temps Réel',
    'organizer.averageLatencyTitle': 'Latence Moyenne',
    'organizer.audioStability': 'Stabilité Audio',
    'organizer.activeListeners': 'Auditeurs Actifs',
    'organizer.onEvents': 'Sur 3 événements',
    'organizer.audioConfiguration': 'Configuration Audio',
    'organizer.audioSettings': 'Paramètres de capture et traitement audio',
    'organizer.audioQuality': 'Qualité Audio',
    'organizer.audioQualityValue': '48kHz / 16-bit (Recommandé)',
    'organizer.noiseReduction': 'Réduction de Bruit',
    'organizer.noiseReductionValue': 'Activée (IA Adaptive)',
    'organizer.security': 'Sécurité',
    'organizer.securitySettings': 'Chiffrement et gestion des accès',
    'organizer.encryption': 'Chiffrement',
    'organizer.encryptionValue': 'AES-256 bout en bout',
    'organizer.listenerAccess': 'Accès Auditeurs',
    'organizer.listenerAccessValue': 'Code QR sécurisé',
    
    // Organizer workflow
    'organizer.workflow.create': 'Créer',
    
    // Speaker/Broadcaster interface
    'speaker.title': 'Interface Orateur',
    'speaker.subtitle': 'Diffusion et contrôle de la traduction en temps réel',
    'speaker.loginEvent': 'Démarrer la diffusion',
    'speaker.eventKey': 'Entrez la clé de diffusion',
    'speaker.eventKeyPlaceholder': 'Entrez la clé de diffusion de l\'événement',
    'speaker.audioSetup': 'Configuration Audio',
    'speaker.selectDevice': 'Sélectionner le périphérique d\'entrée',
    'speaker.volumeMeter': 'Niveau sonore',
    'speaker.testAudio': 'Tester',
    'speaker.sourceLanguage': 'Langue source',
    'speaker.confirmLanguage': 'Confirmer la langue',
    'speaker.broadcast': 'Diffusion',
    'speaker.startBroadcast': 'Démarrer la diffusion',
    'speaker.stopBroadcast': 'Arrêter la diffusion',
    'speaker.broadcasting': 'Diffusion en cours...',
    'speaker.monitoring': 'Monitoring en temps réel',
    'speaker.latency': 'Latence',
    'speaker.pipelineHealth': 'État du pipeline',
    'speaker.connectedParticipants': 'Participants connectés',
    'speaker.healthy': 'Sain',
    'speaker.degraded': 'Dégradé',
    'speaker.offline': 'Hors ligne',
    'speaker.testParticipantView': 'Tester la vue participant',
    'speaker.openParticipantView': 'Ouvrir vue participant',
    'speaker.security': 'Sécurité',
    'speaker.broadcastKey': 'Clé de diffusion requise',
    'speaker.goLive': 'Passer en direct',
    'speaker.unauthorized': 'Non autorisé',
    'speaker.devicePermissions': 'Permissions micro requises',
    'organizer.workflow.share': 'Partager',
    'organizer.workflow.monitor': 'Surveiller',
    'organizer.workflow.eventTitle': 'Titre de l\'événement',
    'organizer.workflow.eventTitlePlaceholder': 'Ex: Conférence Tech 2024',
    'organizer.workflow.eventDate': 'Date et heure (optionnel)',
    'organizer.workflow.sourceLanguage': 'Langue source',
    'organizer.workflow.targetLanguages': 'Langues de traduction',
    'organizer.workflow.eventType': 'Type d\'événement',
    'organizer.workflow.eventTypePublic': 'Public',
    'organizer.workflow.eventTypePrivate': 'Protégé par mot de passe',
    'organizer.workflow.createEventButton': 'Créer l\'événement',
    'organizer.workflow.accessGenerated': 'Accès généré',
    'organizer.workflow.qrCodeTitle': 'QR Code',
    'organizer.workflow.shareableLink': 'Lien de partage',
    'organizer.workflow.copyLink': 'Copier le lien',
    'organizer.workflow.downloadQR': 'Télécharger QR',
    'organizer.workflow.eventCode': 'Code événement',
    'organizer.workflow.connectedParticipants': 'Participants connectés',
    'organizer.workflow.languageBreakdown': 'Répartition par langue',
    'organizer.workflow.backToCreate': 'Créer un nouvel événement',
    'organizer.workflow.eventSettings': 'Paramètres de l\'événement',
    
    // Events List View
    'organizer.events.loading': 'Chargement...',
    'organizer.events.totalEvents': 'Total Événements',
    'organizer.events.activeEvents': 'Événements Actifs',
    'organizer.events.scheduledEvents': 'Programmés',
    'organizer.events.myEvents': 'Mes Événements',
    'organizer.events.manageDescription': 'Gérez tous vos événements de traduction',
    'organizer.events.searchPlaceholder': 'Rechercher un événement...',
    'organizer.events.allStatuses': 'Tous les statuts',
    'organizer.events.status.draft': 'Brouillon',
    'organizer.events.status.scheduled': 'Programmé',
    'organizer.events.status.active': 'Actif',
    'organizer.events.status.ended': 'Terminé',
    'organizer.events.status.archived': 'Archivé',
    'organizer.events.table.status': 'Statut',
    'organizer.events.table.title': 'Titre',
    'organizer.events.table.date': 'Date',
    'organizer.events.table.languages': 'Langues',
    'organizer.events.table.participants': 'Participants',
    'organizer.events.table.actions': 'Actions',
    'organizer.events.noEvents': 'Aucun événement trouvé',
    'organizer.events.notScheduled': 'Non programmé',
    'organizer.events.action.viewQR': 'Voir QR Code',
    'organizer.events.action.start': 'Démarrer',
    'organizer.events.action.end': 'Terminer',
    'organizer.events.action.archive': 'Archiver',
    'organizer.events.action.delete': 'Supprimer',
    'organizer.events.deleteTitle': 'Supprimer cet événement ?',
    'organizer.events.deleteDescription': 'Cette action est irréversible. Tous les participants et données associées seront supprimés.',
    'organizer.events.cancel': 'Annuler',
    'organizer.events.confirmDelete': 'Supprimer',
    'organizer.events.updated': 'Événement mis à jour',
    'organizer.events.deleted': 'Événement supprimé',
    'organizer.events.updateError': 'Erreur lors de la mise à jour',
    'organizer.events.deleteError': 'Erreur lors de la suppression',
    
    // Create Event View
    'organizer.create.title': 'Créer un Nouvel Événement',
    'organizer.create.description': 'Configurez les paramètres de votre événement de traduction en temps réel',
    'organizer.create.eventTitle': 'Titre de l\'événement *',
    'organizer.create.eventTitlePlaceholder': 'Ex: Conférence Tech 2025',
    'organizer.create.eventDate': 'Date et heure (optionnel)',
    'organizer.create.chooseDate': 'Choisir une date',
    'organizer.create.dateNote': 'Si non spécifié, l\'événement sera actif immédiatement',
    'organizer.create.sourceLanguage': 'Langue source *',
    'organizer.create.targetLanguages': 'Langues de traduction *',
    'organizer.create.eventType': 'Type d\'événement *',
    'organizer.create.publicType': 'Public - Accessible à tous avec le code',
    'organizer.create.privateType': 'Privé - Protégé par mot de passe (bientôt disponible)',
    'organizer.create.creating': 'Création...',
    'organizer.create.createButton': 'Créer l\'Événement',
    'organizer.create.success': 'Événement créé avec succès !',
    'organizer.create.error': 'Erreur lors de la création de l\'événement',
    'organizer.create.titleTooShort': 'Titre trop court',
    'organizer.create.titleTooLong': 'Titre trop long',
    'organizer.create.languageRequired': 'Au moins une langue cible requise',
    
    // Account View
    'organizer.account.eventsCreated': 'Événements créés',
    'organizer.account.totalParticipants': 'Participants totaux',
    'organizer.account.memberSince': 'Membre depuis',
    'organizer.account.accountInfo': 'Informations du compte',
    'organizer.account.accountDescription': 'Gérez vos informations personnelles',
    'organizer.account.email': 'Email',
    'organizer.account.fullName': 'Nom complet',
    'organizer.account.fullNamePlaceholder': 'Votre nom complet',
    'organizer.account.company': 'Entreprise',
    'organizer.account.companyPlaceholder': 'Nom de votre entreprise',
    'organizer.account.updateProfile': 'Mettre à jour le profil (bientôt disponible)',
    'organizer.account.settings': 'Paramètres',
    'organizer.account.emailNotifications': 'Notifications email',
    'organizer.account.emailNotificationsDesc': 'Recevoir des notifications pour les événements',
    'organizer.account.changePassword': 'Changer le mot de passe',
    'organizer.account.changePasswordDesc': 'Modifier votre mot de passe de connexion',
    'organizer.account.comingSoon': 'Bientôt disponible',
    
    // Landing page
    'landing.welcome': 'Bienvenue !',
    'landing.bluetoothInstruction': 'Assurez-vous de connecter votre appareil Bluetooth (oreillettes ou casque).',
    'landing.quickStart': 'Prise en main rapide :',
    'landing.step1': '1. Connectez votre appareil audio Bluetooth à votre téléphone.',
    'landing.step2': '2. Vérifiez que le son est bien activé.',
    'landing.step3': '3. Cliquez sur Rejoindre l\'évènement pour démarrer la traduction en direct.',
    'landing.readyMessage': '👉 Vous êtes prêt à vivre l\'expérience Glot en toute simplicité !',
    'landing.joinEvent': 'Rejoindre l\'évènement',
    'landing.learnMore': 'En savoir plus',
    'landing.privacyPolicy': 'Politique de confidentialité',
    'landing.termsOfService': 'Conditions d\'utilisation',
    
    // Common
    'common.language': 'Langue',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.back': 'Retour',
    'common.connected': 'Connecté',
    'common.configure': 'Configurer',
    'common.show': 'Afficher',
    'common.testing': 'Test en cours',
    'common.stable': 'Très stable'
  },
  en: {
    // Navigation
    'nav.joinEvent': 'Join Event',
    'nav.organizer': 'Organizer Space',
    'nav.speakerLink': 'Are you a speaker? Click here',
    
    // Home page
    'home.tagline': 'Access your events, conferences and meetings in the language of your choice.',
    'home.subtitle': 'Connect, translate, and communicate seamlessly across languages in real-time.',
    'home.speakers.title': 'For Speakers',
    'home.speakers.description': 'Intuitive interface to manage your events and monitor translation quality in real time.',
    'home.listeners.title': 'For Listeners',
    'home.listeners.description': 'Simple access via QR code or event code. Listen in the language of your choice with minimal latency.',
    'home.privacyPolicy': 'Privacy Policy',
    'home.termsOfService': 'Terms of Service',
    
    // Listener page
    'listener.joinEvent': 'Join Event',
    'listener.eventCode': 'Event Code',
    'listener.eventCodePlaceholder': 'Enter event code',
    'listener.selectLanguage': 'Select your language',
    'listener.connect': 'Connect',
    'listener.scanQR': 'Scan QR Code',
    'listener.deviceInfo': 'Compatible with all modern devices',
    'listener.live': 'LIVE',
    'listener.disconnect': 'Disconnect',
    'listener.audioPlayer': 'Audio Player',
    'listener.volume': 'Volume',
    'listener.latency': 'Latency',
    'listener.listeners': 'Listeners',
    'listener.quality': 'Quality',
    'listener.switchLanguage': 'Switch Language',
    'listener.ms': 'ms',
    'listener.excellent': 'Excellent',
    'listener.realTimeTranslation': 'Real-time translation',
    'listener.connection': 'Connection',
    'listener.providedByOrganizer': 'Code provided by organizer',
    'listener.enterCode': 'Ex: TECH2024-EN',
    'listener.translationLanguage': 'Translation Language',
    'listener.scanQRCode': 'Scan QR Code',
    'listener.scanQRDescription': 'Scan the QR code displayed by the organizer',
    'listener.deviceCompatibility': 'Compatible with smartphone, tablet and computer',
    'listener.encryption': '🔒 End-to-end encryption • 📱 Compatible with all devices',
    'listener.invalidEventCode': 'Invalid event code',
    'listener.languageNotAvailable': 'Selected language is not available for this event',
    'listener.connectionError': 'Unable to connect. Please try again',
    
    // Landing page
    'landing.welcome': 'Welcome!',
    'landing.bluetoothInstruction': 'Make sure to connect your Bluetooth device (earphones or headset).',
    'landing.quickStart': 'Quick start:',
    'landing.step1': '1. Connect your Bluetooth audio device to your phone.',
    'landing.step2': '2. Check that the sound is enabled.',
    'landing.step3': '3. Click Join Event to start live translation.',
    'landing.readyMessage': '👉 You\'re ready to experience Glot with ease!',
    'landing.joinEvent': 'Join Event',
    'landing.learnMore': 'Learn More',
    'landing.privacyPolicy': 'Privacy Policy',
    'landing.termsOfService': 'Terms of Service',
    
    // Organizer page
    'organizer.dashboard': 'Dashboard',
    'organizer.dashboardTitle': 'Glot Dashboard',
    'organizer.dashboardSubtitle': 'Manage your events and monitor your translation sessions.',
    'organizer.title': 'Organizer Space',
    'organizer.subtitle': 'Manage your simultaneous translation events',
    'organizer.tabs.events': 'Events',
    'organizer.tabs.myEvents': 'My Events',
    'organizer.tabs.create': 'Create',
    'organizer.tabs.stats': 'Stats',
    'organizer.tabs.account': 'My Account',
    'organizer.logout': 'Log Out',
    'organizer.supabaseRequired': 'Supabase Activation Required',
    'organizer.supabaseDescription': 'To use full features (authentication, event management, database), activate Supabase integration by clicking the green button in the top right.',
    'organizer.tabs.glossaries': 'Glossaries',
    'organizer.tabs.monitoring': 'Monitoring',
    'organizer.tabs.settings': 'Settings',
    'organizer.myEvents': 'My Events',
    'organizer.createEvent': 'Create Event',
    'organizer.active': 'Active',
    'organizer.scheduled': 'Scheduled',
    'organizer.languages': 'Languages',
    'organizer.listeners': 'Listeners',
    'organizer.participants': 'Participants',
    'organizer.latency': 'Latency',
    'organizer.qrCode': 'QR Code',
    'organizer.glossary': 'Glossary',
    'organizer.actions': 'Actions',
    'organizer.connected': 'connected',
    'organizer.expected': 'expected',
    'organizer.averageLatency': 'average',
    'organizer.specializedGlossaries': 'Specialized Glossaries',
    'organizer.createGlossary': 'Create Glossary',
    'organizer.terms': 'terms',
    'organizer.lastUpdate': 'Last update',
    'organizer.realTimeMonitoring': 'Real-Time Monitoring',
    'organizer.averageLatencyTitle': 'Average Latency',
    'organizer.audioStability': 'Audio Stability',
    'organizer.activeListeners': 'Active Listeners',
    'organizer.onEvents': 'On 3 events',
    'organizer.audioConfiguration': 'Audio Configuration',
    'organizer.audioSettings': 'Audio capture and processing settings',
    'organizer.audioQuality': 'Audio Quality',
    'organizer.audioQualityValue': '48kHz / 16-bit (Recommended)',
    'organizer.noiseReduction': 'Noise Reduction',
    'organizer.noiseReductionValue': 'Enabled (AI Adaptive)',
    'organizer.security': 'Security',
    'organizer.securitySettings': 'Encryption and access management',
    'organizer.encryption': 'Encryption',
    'organizer.encryptionValue': 'AES-256 end-to-end',
    'organizer.listenerAccess': 'Listener Access',
    'organizer.listenerAccessValue': 'Secure QR code',
    
    // Organizer workflow
    'organizer.workflow.create': 'Create',
    'organizer.workflow.share': 'Share',
    'organizer.workflow.monitor': 'Monitor',
    
    // Speaker/Broadcaster interface
    'speaker.title': 'Speaker Interface',
    'speaker.goLive': 'Go Live as Speaker',
    'speaker.subtitle': 'Real-time broadcast and translation control',
    'speaker.loginEvent': 'Start Broadcasting',
    'speaker.eventKey': 'Enter the broadcast key',
    'speaker.eventKeyPlaceholder': 'Enter event broadcast key',
    'speaker.audioSetup': 'Audio Setup',
    'speaker.selectDevice': 'Select input device',
    'speaker.volumeMeter': 'Volume level',
    'speaker.testAudio': 'Test',
    'speaker.sourceLanguage': 'Source language',
    'speaker.confirmLanguage': 'Confirm language',
    'speaker.broadcast': 'Broadcast',
    'speaker.startBroadcast': 'Start Broadcast',
    'speaker.stopBroadcast': 'Stop Broadcast',
    'speaker.broadcasting': 'Broadcasting...',
    'speaker.monitoring': 'Real-time Monitoring',
    'speaker.latency': 'Latency',
    'speaker.pipelineHealth': 'Pipeline Status',
    'speaker.connectedParticipants': 'Connected Participants',
    'speaker.healthy': 'Healthy',
    'speaker.degraded': 'Degraded',
    'speaker.offline': 'Offline',
    'speaker.testParticipantView': 'Test participant view',
    'speaker.openParticipantView': 'Open participant view',
    'speaker.security': 'Security',
    'speaker.broadcastKey': 'Broadcast key required',
    'speaker.unauthorized': 'Unauthorized',
    'speaker.devicePermissions': 'Microphone permissions required',
    'organizer.workflow.eventTitle': 'Event title',
    'organizer.workflow.eventTitlePlaceholder': 'Ex: Tech Conference 2024',
    'organizer.workflow.eventDate': 'Date and time (optional)',
    'organizer.workflow.sourceLanguage': 'Source language',
    'organizer.workflow.targetLanguages': 'Translation languages',
    'organizer.workflow.eventType': 'Event type',
    'organizer.workflow.eventTypePublic': 'Public',
    'organizer.workflow.eventTypePrivate': 'Password protected',
    'organizer.workflow.createEventButton': 'Create event',
    'organizer.workflow.accessGenerated': 'Access generated',
    'organizer.workflow.qrCodeTitle': 'QR Code',
    'organizer.workflow.shareableLink': 'Shareable link',
    'organizer.workflow.copyLink': 'Copy link',
    'organizer.workflow.downloadQR': 'Download QR',
    'organizer.workflow.eventCode': 'Event code',
    'organizer.workflow.connectedParticipants': 'Connected participants',
    'organizer.workflow.languageBreakdown': 'Language breakdown',
    'organizer.workflow.backToCreate': 'Create new event',
    'organizer.workflow.eventSettings': 'Event settings',
    
    // Events List View
    'organizer.events.loading': 'Loading...',
    'organizer.events.totalEvents': 'Total Events',
    'organizer.events.activeEvents': 'Active Events',
    'organizer.events.scheduledEvents': 'Scheduled',
    'organizer.events.myEvents': 'My Events',
    'organizer.events.manageDescription': 'Manage all your translation events',
    'organizer.events.searchPlaceholder': 'Search for an event...',
    'organizer.events.allStatuses': 'All statuses',
    'organizer.events.status.draft': 'Draft',
    'organizer.events.status.scheduled': 'Scheduled',
    'organizer.events.status.active': 'Active',
    'organizer.events.status.ended': 'Ended',
    'organizer.events.status.archived': 'Archived',
    'organizer.events.table.status': 'Status',
    'organizer.events.table.title': 'Title',
    'organizer.events.table.date': 'Date',
    'organizer.events.table.languages': 'Languages',
    'organizer.events.table.participants': 'Participants',
    'organizer.events.table.actions': 'Actions',
    'organizer.events.noEvents': 'No events found',
    'organizer.events.notScheduled': 'Not scheduled',
    'organizer.events.action.viewQR': 'View QR Code',
    'organizer.events.action.start': 'Start',
    'organizer.events.action.end': 'End',
    'organizer.events.action.archive': 'Archive',
    'organizer.events.action.delete': 'Delete',
    'organizer.events.deleteTitle': 'Delete this event?',
    'organizer.events.deleteDescription': 'This action is irreversible. All participants and associated data will be deleted.',
    'organizer.events.cancel': 'Cancel',
    'organizer.events.confirmDelete': 'Delete',
    'organizer.events.updated': 'Event updated',
    'organizer.events.deleted': 'Event deleted',
    'organizer.events.updateError': 'Update error',
    'organizer.events.deleteError': 'Deletion error',
    
    // Create Event View
    'organizer.create.title': 'Create a New Event',
    'organizer.create.description': 'Configure your real-time translation event settings',
    'organizer.create.eventTitle': 'Event title *',
    'organizer.create.eventTitlePlaceholder': 'Ex: Tech Conference 2025',
    'organizer.create.eventDate': 'Date and time (optional)',
    'organizer.create.chooseDate': 'Choose a date',
    'organizer.create.dateNote': 'If not specified, the event will be active immediately',
    'organizer.create.sourceLanguage': 'Source language *',
    'organizer.create.targetLanguages': 'Translation languages *',
    'organizer.create.eventType': 'Event type *',
    'organizer.create.publicType': 'Public - Accessible to everyone with the code',
    'organizer.create.privateType': 'Private - Password protected (coming soon)',
    'organizer.create.creating': 'Creating...',
    'organizer.create.createButton': 'Create Event',
    'organizer.create.success': 'Event created successfully!',
    'organizer.create.error': 'Error creating event',
    'organizer.create.titleTooShort': 'Title too short',
    'organizer.create.titleTooLong': 'Title too long',
    'organizer.create.languageRequired': 'At least one target language required',
    
    // Account View
    'organizer.account.eventsCreated': 'Events Created',
    'organizer.account.totalParticipants': 'Total Participants',
    'organizer.account.memberSince': 'Member Since',
    'organizer.account.accountInfo': 'Account Information',
    'organizer.account.accountDescription': 'Manage your personal information',
    'organizer.account.email': 'Email',
    'organizer.account.fullName': 'Full Name',
    'organizer.account.fullNamePlaceholder': 'Your full name',
    'organizer.account.company': 'Company',
    'organizer.account.companyPlaceholder': 'Your company name',
    'organizer.account.updateProfile': 'Update profile (coming soon)',
    'organizer.account.settings': 'Settings',
    'organizer.account.emailNotifications': 'Email notifications',
    'organizer.account.emailNotificationsDesc': 'Receive notifications for events',
    'organizer.account.changePassword': 'Change password',
    'organizer.account.changePasswordDesc': 'Modify your login password',
    'organizer.account.comingSoon': 'Coming soon',
    
    // Common
    'common.language': 'Language',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.connected': 'Connected',
    'common.configure': 'Configure',
    'common.show': 'Show',
    'common.excellent': 'Excellent',
    'common.stable': 'Very stable',
    'common.testing': 'Testing'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<InterfaceLanguage>(() => {
    // Check localStorage for saved language preference
    const savedLanguage = localStorage.getItem('glot-interface-language');
    return (savedLanguage as InterfaceLanguage) || 'fr';
  });

  const handleSetLanguage = (lang: InterfaceLanguage) => {
    setLanguage(lang);
    localStorage.setItem('glot-interface-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};