// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://intjimzcjtusiotahzot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludGppbXpjanR1c2lvdGFoem90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzUyMzgsImV4cCI6MjA3Mzg1MTIzOH0.DsLP5Nwcj4THf723y9pZITcNejcGXtCXjXauT8KH5rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});